window.SitePublicCopy = window.SitePublicCopy || {};
window.SitePublicCopy.fr = {
  common: {
    kofiAlt: "Soutenir Lumiere Studio sur Ko-fi",
    navAriaLabel: "Navigation principale",
    links: {
      home: "Accueil",
      app: "Application",
      guide: "Guide",
      presets: "Presets",
      faq: "FAQ"
    }
  },
  pages: {
    index: {
      meta: {
        title: "Plan de studio photo desktop, tablette et mobile | Lumiere Studio",
        description: "Preparez un plan de studio photo sur desktop, tablette ou mobile avec bibliotheque repliable, vue plan/iso commutable, mesures automatiques, copie d image, export PNG ou PDF et presets.",
        ogTitle: "Lumiere Studio - Plan de studio photo desktop, tablette et mobile",
        ogDescription: "Une seule application web pour construire un set sur desktop, l ajuster sur tablette ou mobile, basculer entre plan et iso et partager un schema propre.",
        twitterTitle: "Lumiere Studio - Plan de studio photo desktop, tablette et mobile",
        twitterDescription: "Bibliotheque repliable, plan/iso commutables, mesures utiles et sortie rapide en image, PNG ou PDF.",
        ogImageAlt: "Capture de l application Lumiere Studio avec bibliotheque, vue principale commutable et mesures"
      },
      topCopy: "La version actuelle fonctionne sur desktop, tablette et mobile. Si elle vous aide, soutenez son evolution.",
      brandTagline: "Photo Studio Planner",
      navItems: ["app", "guide", "presets", "faq"],
      footerItems: ["app", "guide", "presets", "faq"],
      sections: {
        heroCopyContent: `<p class="eyebrow">Plan de studio photo desktop, tablette et mobile</p><h1>Construisez votre set sur desktop, ajustez-le sur tablette ou mobile, puis partagez un plan propre en quelques secondes.</h1><p>Lumiere Studio sert a preparer vite un plateau lisible : placer les elements, verifier les distances utiles, choisir la bonne vue et sortir un document clair pour l'equipe.</p><div class="hero-actions"><a class="button-link primary" href="app.html">Ouvrir l'application</a><a class="button-link secondary" href="guide.html">Lire le guide</a></div><div class="hero-points"><div class="point-chip"><strong>Une seule app</strong>La meme scene fonctionne sur desktop, tablette et mobile, sans version separee.</div><div class="point-chip"><strong>Bibliotheque repliable</strong>En format compact, ouvrez ou masquez la bibliotheque pour recuperer toute la zone utile.</div><div class="point-chip"><strong>Plan / Iso commutables</strong>Choisissez a tout moment quelle vue doit devenir la vue principale, puis zoomez a la molette ou au pinch.</div><div class="point-chip"><strong>Mesures + exports</strong>Affichez les distances cles, copiez l'image, exportez un PNG ou un PDF et gardez vos presets perso.</div></div>`,
        heroVisualContent: `<figure><img src="docs/screenshots/studio-portrait.png" alt="Exemple de plan de studio photo avec bibliotheque, vue principale commutable et mesures dans Lumiere Studio"><figcaption class="hero-caption">Vue principale commutable, bibliotheque repliable en format compact, mesures lisibles et sorties image rapides.</figcaption><div class="meta-list hero-media-meta"><span>Desktop dense</span><span>Tablette compacte</span><span>Mobile tactile</span><span>PNG / PDF</span></div></figure>`,
        introPanelContent: `<p class="eyebrow">Un seul outil du brief au plateau</p><h2>Travaillez large sur ordinateur, puis gardez l'essentiel sous la main sur ecran tactile.</h2><p>Sur desktop, la bibliotheque et les reglages restent visibles pour construire vite. Sur tablette et mobile, l'interface se compacte, la bibliotheque peut se replier et le pinch permet de zoomer sans perdre la scene.</p><p>Vous gardez exactement le meme plan, les memes presets et les memes exports, quel que soit l'ecran utilise au moment du shooting.</p><div class="keyword-list"><span class="keyword-chip">Desktop dense</span><span class="keyword-chip">Tablette compacte</span><span class="keyword-chip">Mobile tactile</span><span class="keyword-chip">Bibliotheque repliable</span><span class="keyword-chip">Mesures auto</span></div>`,
        featuresHeadContent: `<p class="eyebrow">Ce que vous pouvez faire</p><h2>Construire le plan, verifier les distances et sortir un document propre depuis la meme interface.</h2><p>Les trois blocs ci-dessous resumment le coeur de l'app : adapter l'espace de travail a l'ecran, lire vite les informations utiles, puis partager le setup sans friction.</p>`,
        featureCardsContent: `<article class="info-card"><h3>Surface de travail adaptable</h3><p>Desktop pour construire avec de la place, tablette et mobile pour manipuler l'essentiel sans perdre en lisibilite ni en vitesse.</p><div class="meta-list"><span>Desktop</span><span>Tablette</span><span>Mobile</span></div></article><article class="info-card"><h3>Lecture immediate du setup</h3><p>Le mode Mesure met en avant sujet, camera, fond et sources, pendant que les labels restent lisibles et que la vue principale peut passer de plan a iso.</p><div class="meta-list"><span>Mesures</span><span>Plan / Iso</span><span>Labels clairs</span></div></article><article class="info-card"><h3>Sortie prete pour le brief</h3><p>Copier l'image, telecharger un PNG, sortir un PDF et garder ses presets perso fait partie du flux de travail normal de l'app.</p><div class="meta-list"><span>Copier image</span><span>PNG / PDF</span><span>Presets perso</span></div></article>`,
        capturesHeadContent: `<p class="eyebrow">Exemples de setups</p><h2>Trois types de scenes pour voir comment l'app s'adapte au portrait, au boudoir et a l'interview.</h2><p>Chaque capture montre un usage different : lecture des distances sur un portrait, gestion du mobilier sur un boudoir, et organisation camera + LED sur une interview.</p>`,
        screenshotGridContent: `<article class="shot-card hero-copy"><figure><img src="docs/screenshots/studio-portrait.png" alt="Preset portrait avec mesures cles et vue principale commutable dans Lumiere Studio"><figcaption>Preset portrait avec distances utiles, vue principale choisie selon le besoin et sortie propre pour le brief.</figcaption></figure></article><article class="shot-card hero-copy"><figure><img src="docs/screenshots/studio-boudoir.png" alt="Preset boudoir avec mobilier, fond colore et interface actuelle de Lumiere Studio"><figcaption>Preset boudoir avec mobilier, fond colore et logique compacte coherente sur desktop comme sur tablette.</figcaption></figure></article><article class="shot-card hero-copy"><figure><img src="docs/screenshots/studio-video.png" alt="Preset interview avec camera, panneaux LED et interface actuelle de Lumiere Studio"><figcaption>Preset interview avec axe camera lisible, panneaux LED, mesures rapides et export immediat pour l'equipe.</figcaption></figure></article>`,
        resourcesGridContent: `<article class="article-card"><p class="eyebrow">Guide pratique</p><h2>Une methode simple pour poser sujet, camera et source cle sur un meme plan</h2><p>Le guide explique comment construire un setup lisible, verifier les bonnes distances et partager un plan que l'equipe peut relire vite.</p><ul><li>Construire un plan lisible vite</li><li>Passer du plan a l'iso sans repartir de zero</li></ul><p><a class="button-link secondary" href="guide.html">Lire le guide</a></p></article><article class="article-card"><p class="eyebrow">Banque de presets</p><h2>Des bases credibles pour demarrer plus vite, puis des variantes perso a conserver</h2><p>Chargez un preset de depart, adaptez-le a votre plateau, repliez la bibliotheque si besoin et sauvegardez votre propre version dans le navigateur.</p><ul><li>Portrait, boudoir, corporate, produit et video</li><li>Preset de depart puis variante perso</li></ul><p><a class="button-link secondary" href="presets.html">Explorer les presets</a></p></article><article class="article-card"><p class="eyebrow">Questions frequentes</p><h2>Les reponses utiles sur le mobile, les mesures, la bibliotheque et les exports</h2><p>Retrouvez l'essentiel sur le comportement tactile, le switch plan/iso, les mesures automatiques, les presets et les sorties image.</p><ul><li>Verifier les distances utiles au plateau</li><li>Copier une image propre ou telecharger un PNG</li></ul><p><a class="button-link secondary" href="faq.html">Ouvrir la FAQ</a></p></article>`,
        ctaPanelContent: `<p class="eyebrow">Passez a l'application</p><h2>Chargez un preset, ajustez votre scene puis exportez le plan qui servira au brief ou au montage.</h2><p>Desktop, tablette ou mobile : la meme app conserve vos presets, vos distances et vos sorties image sans changer de logique en cours de route.</p><div class="cta-actions"><a class="button-link primary" href="app.html">Lancer Lumiere Studio</a><a class="button-link secondary" href="https://ko-fi.com/D1D21VSKW5" target="_blank" rel="noreferrer noopener">Soutenir le projet</a></div>`
      },
      footerCopy: "Lumiere Studio · plan de studio photo desktop, tablette et mobile avec vue plan/iso commutable, mesures et exports."
    },
    guide: {
      meta: {
        title: "Guide de plan de studio photo, mesures et workflow | Lumiere Studio",
        description: "Guide rapide pour preparer un plan de studio photo : sujet, camera, lumiere principale, mesures utiles, zoom dans le plateau, presets et export du schema.",
        ogTitle: "Guide de plan de studio photo, mesures et workflow | Lumiere Studio",
        ogDescription: "Une methode simple pour preparer un setup photo ou video, verifier les distances et partager un plan propre avant la seance."
      },
      topCopy: "Une methode claire pour transformer une intention de lumiere en plan de plateau lisible, mesurable et partageable.",
      brandTagline: "Guide de preparation",
      navItems: ["home", "app", "presets", "faq"],
      footerItems: ["home", "app", "presets", "faq"],
      sections: {
        heroCardContent: `<p class="eyebrow">Guide</p><h1>Comment preparer un plan de studio clair, exploitable et facile a transmettre a l'equipe.</h1><p>Le but n'est pas de dessiner un schema abstrait. Il s'agit de placer sujet, camera, source cle, fond et accessoires de controle de facon lisible, avec assez d'informations pour monter le plateau sans hesitation.</p>`,
        guideFirstGridContent: `<article class="article-card"><p class="eyebrow">1. Poser la base</p><h2>Placez le fond, le sujet et l'axe camera avant le reste.</h2><p>Commencez par les reperes qui structurent tout le plan : fond, sujet, orientation de prise de vue. Une fois cette base claire, les sources et accessoires trouvent leur place beaucoup plus vite.</p><ul><li>Choisir un fond coherent avec l'intention</li><li>Garder un axe lisible entre sujet et camera</li></ul></article><article class="article-card"><p class="eyebrow">2. Installer la source cle</p><h2>Ajoutez la lumiere principale avant de multiplier les accessoires.</h2><p>Une grande source bien placee couvre deja beaucoup de cas. Commencez par elle, puis ajoutez reflecteurs, flags ou lumieres secondaires seulement si le rendu ou la circulation le demande.</p><ul><li>Portrait doux : source large a 45 degres</li><li>Interview : axe camera clair et panneau principal simple</li></ul></article><article class="article-card"><p class="eyebrow">3. Verifier les distances utiles</p><h2>Activez Mesure une fois la base en place.</h2><p>Le mode Mesure affiche rapidement les distances sujet camera fond et sources. Cela permet de valider un setup avant de le monter et de parler avec des chiffres plutot qu'avec des impressions.</p><ul><li>Comparer camera sujet et sujet fond</li><li>Verifier la distance de la source principale</li></ul></article>`,
        guideSecondGridContent: `<article class="article-card"><p class="eyebrow">4. Zoomer pour relire le plateau</p><h2>Controlez circulation, collisions et lisibilite sans perdre le cadre general.</h2><p>La molette sur desktop et le pinch sur tablette ou mobile aident a verifier les pieds, le mobilier, les degagements et les details qui comptent avant d'envoyer le plan.</p></article><article class="article-card"><p class="eyebrow">5. Sauvegarder une version de travail</p><h2>Transformez une base en preset adapte a votre studio.</h2><p>Chargez un preset, adaptez-le a votre espace, a votre sujet ou a votre client, puis sauvegardez votre propre variante dans le navigateur pour les prochains shootings.</p></article><article class="article-card"><p class="eyebrow">6. Partager le plan final</p><h2>Copie d'image, PNG, PDF ou impression selon le besoin.</h2><p>Une fois le setup valide, choisissez la sortie la plus utile pour le brief, la feuille de service, le message equipe ou la pre production.</p><p><a class="button-link primary" href="app.html">Ouvrir l'application</a></p></article>`
      },
      footerCopy: "Lumiere Studio · Guide de preparation de plateau photo et video avec mesures et export."
    },
    presets: {
      meta: {
        title: "Presets studio photo et variantes perso | Lumiere Studio",
        description: "Decouvrez les presets de Lumiere Studio pour portrait, boudoir, corporate, produit et video, puis sauvegardez vos propres variantes dans le navigateur.",
        ogTitle: "Presets studio photo et variantes perso | Lumiere Studio",
        ogDescription: "Des presets prets a l'emploi pour preparer un setup photo ou video plus vite, puis sauvegarder vos propres versions."
      },
      topCopy: "Des bases credibles pour aller plus vite, puis des variantes que vous pouvez garder dans votre navigateur.",
      brandTagline: "Presets studio",
      navItems: ["home", "app", "guide", "faq"],
      footerItems: ["home", "app", "guide", "faq"],
      sections: {
        heroCardContent: `<p class="eyebrow">Presets</p><h1>Choisissez une base proche de votre setup reel, puis adaptez-la a votre plateau.</h1><p>Les presets ne remplacent pas votre methode. Ils servent a gagner du temps au depart, a tester une implantation credible, puis a sauvegarder votre propre version une fois le plan stabilise.</p>`,
        presetTopGridContent: `<article class="preset-card info-card"><h3>Portrait, beauty et corporate</h3><p>Des bases efficaces pour headshot, portrait editorial, beaute et portrait professionnel, avec une lecture claire du sujet, de la camera et de la source cle.</p><p><strong>Exemples :</strong> portrait doux 45 degres, beauty clamshell, corporate clean.</p></article><article class="preset-card info-card"><h3>Mode, produit, groupe et interview</h3><p>Des presets structures pour silhouette, catalogue, produit, duo, famille ou video studio, avec un plateau deja organise pour aller vite.</p><p><strong>Exemples :</strong> mode parabolique, packshot table top, interview LED.</p></article><article class="preset-card info-card"><h3>Boudoir, nu artistique et creatif</h3><p>Des scenes plus graphiques ou sensibles avec mobilier, fonds marques, projections et jeux d'ombres pour partir d'une ambiance deja posee.</p><p><strong>Exemples :</strong> boudoir parabolic, nu sculptural hard, shadow play.</p></article>`,
        presetDetailsGridContent: `<article class="article-card"><p class="eyebrow">Choisir une base</p><h2>Prenez le preset qui ressemble le plus a votre intention de depart.</h2><p>Le but n'est pas de trouver un preset parfait, mais une base assez proche pour gagner du temps sur le placement, la circulation et la lecture generale du set.</p></article><article class="article-card"><p class="eyebrow">Sauvegarder votre methode</p><h2>Enregistrez votre propre version quand le setup devient recurrent.</h2><p>Une fois votre variante stabilisee, utilisez le menu Presets pour conserver cette implantation et la rouvrir plus tard dans ce navigateur.</p></article><article class="article-card"><p class="eyebrow">Verifier avant partage</p><h2>Mesurez puis exportez seulement la version qui vous sert vraiment.</h2><p>Activez Mesure pour controler les distances cle, puis sortez un PNG, un PDF ou une image copiee selon la personne qui doit relire le plan.</p></article>`,
        ctaPanelContent: `<p class="eyebrow">Passer a l'action</p><h2>Chargez une base, adaptez la scene, mesurez puis sauvegardez votre version.</h2><p>Chaque element peut etre deplace, tourne, supprime ou exporte. Le preset sert de depart, pas de limite.</p><div class="cta-actions"><a class="button-link primary" href="app.html">Ouvrir l'application</a><a class="button-link secondary" href="guide.html">Voir le guide</a></div>`
      },
      footerCopy: "Lumiere Studio · Presets pour portrait, beauty, boudoir, produit, interview et variantes perso."
    },
    faq: {
      meta: {
        title: "FAQ Lumiere Studio | Mobile, bibliotheque, mesures et exports",
        description: "Questions frequentes sur Lumiere Studio : utilisation mobile et tablette, bibliotheque repliable, vue plan/iso, mesures sujet camera fond, presets personnalises, export PNG ou PDF et langues disponibles.",
        ogTitle: "FAQ Lumiere Studio | Mobile, bibliotheque, mesures et exports",
        ogDescription: "Les reponses rapides sur le tactile, la bibliotheque, les mesures, les presets et les sorties image."
      },
      topCopy: "Les reponses rapides aux questions qu'on se pose avant d'ouvrir le plateau ou d'envoyer le plan a l'equipe.",
      brandTagline: "Questions frequentes",
      navItems: ["home", "app", "guide", "presets"],
      footerItems: ["home", "app", "guide", "presets"],
      sections: {
        heroCardContent: `<p class="eyebrow">FAQ</p><h1>Les reponses utiles avant de preparer, relire ou partager un plan de studio.</h1><p>Cette page rassemble les points les plus pratiques sur le mobile, la bibliotheque, les mesures, les presets, la vue iso et les sorties image.</p>`,
        faqGridContent: `<article class="faq-item"><h3>A quoi sert Lumiere Studio ?</h3><p>L'application permet de construire un plan de studio photo ou video avec bibliotheque d'elements, vue de dessus, vue iso, mesures utiles, presets et export du plan.</p></article><article class="faq-item"><h3>Est-ce utilisable sur tablette et mobile ?</h3><p>Oui. L'application a ete retravaillee pour etre exploitable sur ecran tactile, avec interface compacte, gestes de pinch pour zoomer et actions principales toujours accessibles.</p></article><article class="faq-item"><h3>Peut-on masquer la bibliotheque sur ecran tactile ?</h3><p>Oui. Sur tablette et mobile, un bouton Bibliotheque permet de replier ou de reafficher le panneau pour recuperer plus de place sur le plan.</p></article><article class="faq-item"><h3>Quelles mesures sont disponibles ?</h3><p>Le mode Mesure peut afficher automatiquement les distances entre le sujet, la camera, le fond et les autres elements. Vous pouvez aussi tracer une mesure manuelle.</p></article><article class="faq-item"><h3>Peut-on choisir entre plan et vue iso ?</h3><p>Oui. Les boutons Plan et Iso permettent de definir quelle vue devient la vue principale, selon que vous travaillez l'implantation ou le volume general du set.</p></article><article class="faq-item"><h3>Comment fonctionne le zoom ?</h3><p>Sur desktop, vous pouvez zoomer a la molette et avec les controles visibles. Sur tablette et mobile, le zoom se fait directement au pinch dans la vue principale.</p></article><article class="faq-item"><h3>Peut-on sauvegarder ses propres presets ?</h3><p>Oui. En plus des presets integres, vous pouvez enregistrer vos variantes personnalisees dans le navigateur via le menu Presets.</p></article><article class="faq-item"><h3>Quels exports sont disponibles ?</h3><p>Le menu Fichier permet de copier l'image, exporter en PNG, exporter en PDF et imprimer la vue principale selon le document que vous devez partager.</p></article><article class="faq-item"><h3>Peut-on changer la langue ?</h3><p>Oui. L'interface publique et l'application prennent en charge le francais, l'anglais, l'espagnol, l'allemand et l'arabe.</p></article>`,
        ctaPanelContent: `<p class="eyebrow">Verifier en conditions reelles</p><h2>Ouvrez un preset, ajustez le plan puis testez le comportement qui vous interesse.</h2><p>Le plus simple est de charger une base, de manipuler la bibliotheque, d'activer Mesure puis d'exporter le plan pour valider votre workflow.</p><div class="cta-actions"><a class="button-link primary" href="app.html">Ouvrir l'application</a><a class="button-link secondary" href="presets.html">Voir les presets</a></div>`
      },
      footerCopy: "Lumiere Studio · FAQ de l'application de plan de studio photo, mesures et export PDF."
    }
  }
};
